language: ruby
rvm:
  - 1.9.3
before_script:
  - cp config/database.heroku.yml config/database.yml
  - psql -c 'create database tushiesandtantrums_test;' -U postgres
  - rake db:migrate
  - export RUBY_GC_MALLOC_LIMIT=50000000
